### ISSUE TITLE
Linking

### ISSUE THREAD

**Issue by icidasset** [fission-suite/auth-lobby#15]
Connectivity isn't great, but that's a libp2p thing:
https://github.com/libp2p/js-libp2p/issues/703

We could do websockets on our API in the meantime.
Need to test more and investigate further.

**Comment by dholms** [comment]
We could create a websockets relay with the exact same API as pubsub so they're super easy to switch out when pubsub is more reliable. Or even just fall back to WS if pubsub isn't connecting

**Comment by expede** [comment]
Yeah, I was thinking of adding it as a permanent backup system. Give it the same client interface,  it switch out the implementation (ie an adapter or facade)
