### ISSUE TITLE
Staging — No linking code shown on iOS

### ISSUE THREAD

**Issue by expede** [fission-suite/auth-lobby#25]
# Summary

## Problem

When linking, no numbers/link code is displayed

### Impact

Can’t confirm that linking hasn’t been tampered with

## Solution

Display the code

# Detail

**Describe the bug**

**To Reproduce**
1. Go to `auth.runfission.net` on an iPhone and a second device (NOTE staging)
2. Create an account on the iPhone
3. Click on sign in on the second device
4. Input target username
5. See code on second device, but not on iPhone

**Screenshots**

![5547667A-8B37-4A43-98BE-2DB128C9C7CA](https://user-images.githubusercontent.com/1052016/94322132-7c836180-ff46-11ea-9ae9-d7b3570181c2.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 + iPad Pro
 - OS: iOS 14
 - Browser Safari
 - Version 14?

**Additional context**

**Comment by icidasset** [comment]
More context:

<img width="823" alt="Screenshot 2020-10-23 at 18 42 17" src="https://user-images.githubusercontent.com/296665/97031186-2f53d900-1560-11eb-881a-deee6592b519.png">

Error message:
Could not locate user DID in DNS.
