### ISSUE TITLE
Create a reset link that we can direct users to use when necessary

### ISSUE THREAD

**Issue by bmann** [fission-suite/auth-lobby#31]
Sometimes a user will get in a state where a key is generated but not linked.

Aside from the "remove this device" button when you are logged in, we need a link to help users reset their localstorage / clear things with the Fission auth. Specifically for mobile devices where this is harder to do than on desktop.

Something like `auth.fission.codes/?reset` or similar, that we can direct people to visit.

**Comment by samuelandert** [comment]
Documenting the issue where this occured:
Chrome-App: 86.0.4240.198
OS: Android 10; SSM-A505FN build/QP1A. 190711.020

**Comment by icidasset** [comment]
Added a reset page: https://auth.fission.codes/reset/
Load the page, then go back to home page and everything will be reset.
Can also add an automatic redirect if that's useful?

Apparently there was an issue with the remove-device functionality, which I now fixed.

**Comment by bmann** [comment]
Thanks @icidasset — we can handle in documentation for now.
