### ISSUE TITLE
Give shared worker a name

### ISSUE THREAD

**Issue by icidasset** [fission-suite/auth-lobby#41]
<img width="651" alt="Screenshot 2021-01-31 at 21 23 06" src="https://user-images.githubusercontent.com/296665/106396799-90fecb80-640a-11eb-8bab-5bece3d026af.png">

**Comment by expede** [comment]
Obviously "Marx" 🤣 Web Workers of the world unite!

![](https://memegenerator.net/img/instances/75686730/workers-of-the-world-unite.jpg)

**Comment by icidasset** [comment]
<img width="452" alt="Screenshot 2021-02-11 at 15 38 19" src="https://user-images.githubusercontent.com/296665/107650882-3887c380-6c7f-11eb-9a3f-d0f352448560.png">

Done @expede 😂 👌
