### ISSUE TITLE
Show username on app permission request

### ISSUE THREAD

**Issue by bmann** [fission-suite/auth-lobby#42]
The prompt to the user when they are giving permission to an app doesn't show the username. 

Should have a "logged in as boris_mann" as part of that dialog.

**Comment by icidasset** [comment]
<img width="626" alt="Screenshot 2021-02-11 at 15 20 56" src="https://user-images.githubusercontent.com/296665/107648553-c2825d00-6c7c-11eb-8eb0-47aea3cf01ff.png">

Is this sufficient or should it be more noticeable?

**Comment by bmann** [comment]
looking good!

I think that’s great for now. It’s mostly for developers and others who switch accounts a lot.
