### ISSUE TITLE
Allow redirecting back to file:// urls

### ISSUE THREAD

**Issue by icidasset** [fission-suite/auth-lobby#46]
This'll be difficult as `elm/url` doesn't support the `file` protocol.

**Comment by walkah** [comment]
yeah, `chrome-extension://` is another one. 🤔

**Comment by icidasset** [comment]
Allows all the protocols now, currently on staging.
`chrome-extension://` seems to work, not sure about `file://`

**Comment by icidasset** [comment]
`file://` redirection does not work, browsers don't allow it.
