### ISSUE TITLE
just translate-schemas fails

### ISSUE THREAD

**Issue by matheus23** [fission-suite/auth-lobby#60]
When trying to build the auth lobby, I need the `Theme.elm` file. I noticed that `translate-schemas` generates that file, so I ran it.

However, I need to have `quicktype` installed. Maybe we need to add that to the nix file?

When I install `quicktype` and run `just translate-schemas`, it generates a `Theme.elm` file with some references to `Jpipe.decode`, which leads to an elm compiler error, as that identifier doesn't exist.

When I change `Jpipe.decode` to `Jdec.succeed` manually, it works.

**Comment by icidasset** [comment]
My bad, my quicktype PR is still not merged 😢 

You can install my fork:
https://github.com/icidasset/quicktype/tree/elm-0.19.1

If you want to help nudge the quicktype folks, comment here 😅 
https://github.com/quicktype/quicktype/pull/1653

**Comment by icidasset** [comment]
My quicktype fork is now listed in the NPM dependencies.
