### ISSUE TITLE
/reset should redirect to /reset/ or show the same view

### ISSUE THREAD

**Issue by therealjeffg** [fission-suite/auth-lobby#83]
If I go to `/reset` I just get the default '/' view. I should see the same view as `/reset/` instead.

**Comment by matheus23** [comment]
This would be easier to implement if we had https://github.com/ipfs/go-ipfs/issues/7392

**Comment by therealjeffg** [comment]
@matheus23 so you're saying it's not impossible to implement? I don't understand how the framework works, but usually route aliases are a built-in feature, no?

**Comment by bmann** [comment]
It means we have to do a client side redirect, because we can’t rely on the server. Which we should do @matheus23 unless I also am missing something in Elm Land ;)

**Comment by matheus23** [comment]
We can totally build this by doing a redirect in javascript.
I just wanted to tag the above issue as it would help with this as well :)
In other words: In case the above issue gets implemented before we get to this, we should use that, I think.

**Comment by bmann** [comment]
Native redirects will take a while to get into go-IPFS. 

We may be able to get there sooner with our nginx proxy work and do it at that layer.
